/**
 * seed.mjs — Seed the ConnectMyEvent MongoDB database with sample events
 * Run with: node seed.mjs
 */
import { PrismaClient } from "@prisma/client";

const db = new PrismaClient();

const events = [
  // ─── HACKATHONS ────────────────────────────────────────────────
  {
    title: "CodeStorm 2026",
    category: "hackathon",
    categoryLabel: "Hackathon",
    date: "Jul 15, 2026",
    location: "Mumbai",
    format: "offline",
    price: "free",
    priceAmount: "Free",
    organizer: "TechCorp India",
    icon: "💻",
    color: "#6366f1",
    bgColor: "#eef2ff",
    description: "A 36-hour hackathon focused on AI/ML solutions for healthcare. Build tools that save lives and win big prizes.",
    prizes: "₹5,00,000",
    registrationsCount: 142,
    viewsCount: 980,
    daysLeft: 20,
    teamSize: "2-4 Members",
    featured: true,
    timeline: [],
    schedule: [],
    speakers: [],
    sponsors: [],
  },
  {
    title: "WebDev Showdown",
    category: "hackathon",
    categoryLabel: "Hackathon",
    date: "Jul 28, 2026",
    location: "Hyderabad",
    format: "offline",
    price: "free",
    priceAmount: "Free",
    organizer: "Dev Community Hub",
    icon: "💻",
    color: "#6366f1",
    bgColor: "#eef2ff",
    description: "48-hour web development competition. Build a full-stack app from scratch and win cash prizes and mentorship opportunities.",
    prizes: "₹3,00,000",
    registrationsCount: 150,
    viewsCount: 750,
    daysLeft: 33,
    teamSize: "2-5 Members",
    featured: false,
    timeline: [],
    schedule: [],
    speakers: [],
    sponsors: [],
  },
  {
    title: "HackForIndia 2026",
    category: "hackathon",
    categoryLabel: "Hackathon",
    date: "Aug 10, 2026",
    location: "Bangalore",
    format: "offline",
    price: "free",
    priceAmount: "Free",
    organizer: "Google Developer Groups",
    icon: "💻",
    color: "#6366f1",
    bgColor: "#eef2ff",
    description: "India's premier student hackathon sponsored by Google. Solve real-world problems using Google Cloud, Firebase, and AI tools.",
    prizes: "₹10,00,000",
    registrationsCount: 512,
    viewsCount: 2100,
    daysLeft: 46,
    teamSize: "2-4 Members",
    featured: true,
    timeline: [],
    schedule: [],
    speakers: [],
    sponsors: [],
  },
  {
    title: "Blockchain Decoded",
    category: "hackathon",
    categoryLabel: "Hackathon",
    date: "Aug 22, 2026",
    location: "Online (Virtual)",
    format: "online",
    price: "free",
    priceAmount: "Free",
    organizer: "BITS Pilani Web3 Club",
    icon: "💻",
    color: "#6366f1",
    bgColor: "#eef2ff",
    description: "Build decentralized apps using Solidity, Ethereum, and Layer-2 solutions. Beginner-friendly tracks included.",
    prizes: "₹2,50,000",
    registrationsCount: 88,
    viewsCount: 420,
    daysLeft: 58,
    teamSize: "1-3 Members",
    featured: false,
    timeline: [],
    schedule: [],
    speakers: [],
    sponsors: [],
  },

  // ─── WORKSHOPS ────────────────────────────────────────────────
  {
    title: "Cloud Architecture Masterclass",
    category: "workshop",
    categoryLabel: "Workshop",
    date: "Aug 3, 2026",
    location: "Bangalore",
    format: "offline",
    price: "paid",
    priceAmount: "₹499",
    organizer: "CloudSkills Academy",
    icon: "🛠️",
    color: "#0ea5e9",
    bgColor: "#e0f2fe",
    description: "Hands-on workshop on designing scalable cloud architectures using AWS and GCP. Earn an industry-recognised certification.",
    prizes: "Certification Voucher",
    registrationsCount: 38,
    viewsCount: 310,
    daysLeft: 39,
    teamSize: "Individual",
    featured: false,
    timeline: [],
    schedule: [],
    speakers: [],
    sponsors: [],
  },
  {
    title: "React & Next.js Bootcamp",
    category: "workshop",
    categoryLabel: "Workshop",
    date: "Aug 17, 2026",
    location: "Online (Virtual)",
    format: "online",
    price: "free",
    priceAmount: "Free",
    organizer: "Frontend Masters India",
    icon: "🛠️",
    color: "#0ea5e9",
    bgColor: "#e0f2fe",
    description: "A 2-day intensive bootcamp covering React 19, Next.js 15, server components, and production deployment strategies.",
    prizes: "Certificate of Completion",
    registrationsCount: 220,
    viewsCount: 890,
    daysLeft: 53,
    teamSize: "Individual",
    featured: false,
    timeline: [],
    schedule: [],
    speakers: [],
    sponsors: [],
  },

  // ─── JOB FAIRS ────────────────────────────────────────────────
  {
    title: "TechTalent Career Expo 2026",
    category: "jobfair",
    categoryLabel: "Job Fair",
    date: "Sep 5, 2026",
    location: "Delhi",
    format: "offline",
    price: "free",
    priceAmount: "Free",
    organizer: "PlacementPro India",
    icon: "💼",
    color: "#10b981",
    bgColor: "#d1fae5",
    description: "Connect with 80+ top recruiters from Microsoft, Infosys, Wipro, Zomato and more. Resume review desks, mock interviews, and on-spot offers.",
    prizes: "On-spot Offers",
    registrationsCount: 1240,
    viewsCount: 5600,
    daysLeft: 72,
    teamSize: "Individual",
    featured: true,
    timeline: [],
    schedule: [],
    speakers: [],
    sponsors: [],
  },

  // ─── STARTUP PITCHES ─────────────────────────────────────────
  {
    title: "IdeaLaunch Pitch Fest",
    category: "startup",
    categoryLabel: "Startup Pitch",
    date: "Sep 12, 2026",
    location: "Pune",
    format: "offline",
    price: "free",
    priceAmount: "Free",
    organizer: "Startup India Cell",
    icon: "🚀",
    color: "#f59e0b",
    bgColor: "#fef3c7",
    description: "Pitch your startup idea to a panel of top VCs and angel investors. Win seed funding up to ₹25 Lakhs and 6 months of incubation support.",
    prizes: "₹25,00,000 Seed Funding",
    registrationsCount: 72,
    viewsCount: 640,
    daysLeft: 79,
    teamSize: "1-3 Members",
    featured: false,
    timeline: [],
    schedule: [],
    speakers: [],
    sponsors: [],
  },

  // ─── CONFERENCES ──────────────────────────────────────────────
  {
    title: "AI/ML Summit 2026",
    category: "hackathon",
    categoryLabel: "Hackathon",
    date: "Sep 20, 2026",
    location: "Delhi",
    format: "offline",
    price: "paid",
    priceAmount: "₹999",
    organizer: "AI India Foundation",
    icon: "💻",
    color: "#6366f1",
    bgColor: "#eef2ff",
    description: "India's largest AI conference featuring keynotes from industry leaders, research paper presentations, and hands-on AI tool demos.",
    prizes: "N/A",
    registrationsCount: 312,
    viewsCount: 1800,
    daysLeft: 87,
    teamSize: "Individual",
    featured: false,
    timeline: [],
    schedule: [],
    speakers: [],
    sponsors: [],
  },

  // ─── NGO / VOLUNTEER ─────────────────────────────────────────
  {
    title: "GreenEarth Volunteer Drive",
    category: "volunteer",
    categoryLabel: "Volunteer Drive",
    date: "Jul 20, 2026",
    location: "Chennai",
    format: "offline",
    price: "free",
    priceAmount: "Free",
    organizer: "Eco Warriors Foundation",
    icon: "🤝",
    color: "#22c55e",
    bgColor: "#dcfce7",
    description: "Join 500+ volunteers in a massive city-wide tree plantation and beach clean-up drive. Certificate of participation provided.",
    prizes: "Certificate + T-Shirt",
    registrationsCount: 480,
    viewsCount: 2200,
    daysLeft: 25,
    teamSize: "Individual",
    featured: false,
    timeline: [],
    schedule: [],
    speakers: [],
    sponsors: [],
  },

  // ─── SCHOLARSHIPS ─────────────────────────────────────────────
  {
    title: "Merit Tech Scholarship 2026",
    category: "scholarship",
    categoryLabel: "Scholarship",
    date: "Aug 30, 2026",
    location: "Online (Virtual)",
    format: "online",
    price: "free",
    priceAmount: "Free",
    organizer: "Tata Trusts Education",
    icon: "🎓",
    color: "#8b5cf6",
    bgColor: "#ede9fe",
    description: "Apply for the Merit Tech Scholarship covering full tuition fees for B.Tech / MCA students with outstanding academic performance.",
    prizes: "Up to ₹1,50,000",
    registrationsCount: 890,
    viewsCount: 4200,
    daysLeft: 66,
    teamSize: "Individual",
    featured: true,
    timeline: [],
    schedule: [],
    speakers: [],
    sponsors: [],
  },

  // ─── CULTURAL ─────────────────────────────────────────────────
  {
    title: "Culturama Fest 2026",
    category: "cultural",
    categoryLabel: "Cultural Event",
    date: "Sep 3, 2026",
    location: "Jaipur",
    format: "offline",
    price: "paid",
    priceAmount: "₹199",
    organizer: "Rajasthan Youth Council",
    icon: "🎭",
    color: "#ec4899",
    bgColor: "#fce7f3",
    description: "A 3-day mega cultural festival with dance, music, street art, stand-up comedy, and film screenings celebrating India's diversity.",
    prizes: "Trophies + Cash",
    registrationsCount: 620,
    viewsCount: 3100,
    daysLeft: 70,
    teamSize: "1-10 Members",
    featured: false,
    timeline: [],
    schedule: [],
    speakers: [],
    sponsors: [],
  },
];

async function seed() {
  console.log(`Seeding ${events.length} events into MongoDB...`);

  // Clear existing events first
  const deleted = await db.event.deleteMany({});
  console.log(`Cleared ${deleted.count} existing events.`);

  // Insert all events
  let created = 0;
  for (const event of events) {
    await db.event.create({ data: event });
    console.log(`  [OK] Created: ${event.title}`);
    created++;
  }

  console.log(`\nDone! Seeded ${created} events successfully.`);
  await db.$disconnect();
}

seed().catch((err) => {
  console.error("Seed failed:", err.message);
  db.$disconnect();
  process.exit(1);
});
